### ISSUE TITLE
Is there a way to run the code for any random image with a random question?

### ISSUE THREAD

**Issue by BAILOOL** [jacobandreas/nmn2#13]

**Comment by jacobandreas** [comment]
Not easily, but you can always create a new version of the VQA dataset and
add your question and image.

On Wed, Nov 23, 2016 at 3:10 AM Alex Bailo notifications@github.com wrote:

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
https://github.com/jacobandreas/nmn2/issues/13, or mute the thread
