### ISSUE TITLE
the output of question parsing

### ISSUE THREAD

**Issue by cloud-waiting-for-wind** [jacobandreas/nmn2#15]
I am not sure, but  it  seems that the output of question parsing don't match the paper.
For example, according to the paper, "Is there a red shape above a circle?" this question  should be transformed into :
 measure[is](combine[and](find[red],transform[above](find[circle]))) 
or  is(and(red,above(circle))

but the output of parser script is   
(is shape);(is circle);(is (and shape circle))

"what is stuffed with toothbrushes wrapped in plastic?" should bu transformed into 
describe[what](find[stuff])
or what(stuff)

but  the output of parser script is  
(what toothbrush);(what wrap);(what (and toothbrush wrap))

It seems that  only simple question such as "what color is the vase? "  or "is this a clock?" can the parser script get right answer.

**Comment by jacobandreas** [comment]
For the NAACL paper I modified the VQA parsing script to be more consistent
with what we do in the Geo domain. In our experiments, parsing changes
alone didn't have a significant effect on performance. I've added the old
script as `parse.old.py` in the `extras` directory if you want to take a
look.

On Tue, Dec 20, 2016 at 12:06 AM cloud-waiting-for-wind <
notifications@github.com> wrote:

I am not sure, but it seems that the output of question parsing don't match
the paper.
For example, according to the paper, "Is there a red shape above a circle?"
this question should be transformed into :
measureis
or is(and(red,above(circle))

but the output of parser script is
(is shape);(is circle);(is (and shape circle))

"what is stuffed with toothbrushes wrapped in plastic?" should bu
transformed into
describewhat
or what(stuff)

but the output of parser script is
(what toothbrush);(what wrap);(what (and toothbrush wrap))

It seems that only simple question such as "what color is the vase? " or
"is this a clock?" can the parser script get right answer.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/jacobandreas/nmn2/issues/15>, or mute the thread
